#!/usr/bin/env node
import p from"node:fs";import u from"node:path";import{fileURLToPath as R}from"node:url";import{execFileSync as g}from"node:child_process";import T from"node:crypto";import U from"node:fs";import _ from"node:readline";function w(){let e=process.stdin.isTTY,o=e?null:U.readFileSync(0,"utf8").split(`
`),t=e?_.createInterface({input:process.stdin,output:process.stdout}):null;function n(i){if(!e){process.stdout.write(i);let c=(o.shift()??"").trim();return process.stdout.write(c+`
`),Promise.resolve(c)}return t||(t=_.createInterface({input:process.stdin,output:process.stdout})),new Promise(c=>{t.question(i,s=>c(s.trim()))})}function a(){t?.close(),t=null}function r(i){if(!e)return process.stdout.write(i+`
`),Promise.resolve((o.shift()??"").trim());if(t)throw new Error("closeLineReader() must be called before the first askHidden()");return new Promise(c=>{let s=process.stdin;process.stdout.write(i);let m=s.isRaw;s.setRawMode(!0),s.resume(),s.setEncoding("utf8");let l="",f=d=>{switch(d){case`
`:case"\r":case"":s.setRawMode(m),s.pause(),s.removeListener("data",f),process.stdout.write(`
`),c(l);break;case"":process.stdout.write(`
`),process.exit(1);break;case"\x7F":case"\b":l.length>0&&(l=l.slice(0,-1),process.stdout.write("\b \b"));break;default:l+=d,process.stdout.write("*");break}};s.on("data",f)})}return{askLine:n,askHidden:r,closeLineReader:a}}var y=u.dirname(R(import.meta.url)),E=u.join(y,".."),S={local:{file:u.join(E,".env.local"),defaultSiteUrl:"http://localhost:3000"},prod:{file:u.join(E,".env.prod"),defaultSiteUrl:"https://your-domain.com"}};function v(){try{let o=g("npx",["--yes","auth","secret"],{cwd:E,stdio:["ignore","pipe","ignore"]}).toString("utf8").match(/BETTER_AUTH_SECRET=(\S+)/);if(o)return o[1]}catch{}return console.warn("Warning: 'npx auth secret' unavailable \u2014 generating AUTH_SECRET locally instead."),T.randomBytes(32).toString("base64")}function I(e){let o={};if(!p.existsSync(e))return o;for(let t of p.readFileSync(e,"utf8").split(`
`)){let n=t.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);n&&(o[n[1]]=n[2])}return o}function h(e,o){let t=Object.entries(o).map(([n,a])=>`${n}=${a}`);p.writeFileSync(e,t.join(`
`)+`
`,{mode:384}),p.chmodSync(e,384)}async function L(e){let o={};for(;;){let t=(await e("Add another env variable? [y/N]: ")).toLowerCase();if(t!=="y"&&t!=="yes")break;let n=await e("Enter as KEY=VALUE: "),a=n.indexOf("=");if(a<=0){console.warn(`Invalid format "${n}" \u2014 expected KEY=VALUE. Try again.`);continue}let r=n.slice(0,a).trim(),i=n.slice(a+1).trim();if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(r)){console.warn(`Invalid key "${r}" \u2014 must start with a letter/underscore and contain only letters, digits, underscores. Try again.`);continue}o[r]=i,console.log(`==> Will set ${r}=${i||"(empty)"}`)}return o}async function A(){let{askLine:e,closeLineReader:o}=w(),t=(process.argv[2]||"").toLowerCase();if(t||(t=(await e("Create env for [local/prod]: ")).toLowerCase()),!S[t]){console.error(`Unknown target "${t||"(empty)"}" \u2014 expected "local" or "prod".`),process.exitCode=1,o();return}let{file:n,defaultSiteUrl:a}=S[t],r=I(n),i=u.relative(process.cwd(),n),c=await e(`MongoDB URI${r.MONGODB_URI?" [keep existing]":""}: `),s=await e(`MongoDB DB name [${r.MONGODB_DB||"portfolio"}]: `),m=await e(`NEXT_PUBLIC_SITE_URL [${r.NEXT_PUBLIC_SITE_URL||a}]: `),l=await L(e);o();let f=r.AUTH_SECRET||v();r.AUTH_SECRET?console.log("==> Keeping existing AUTH_SECRET (re-run would invalidate active admin sessions)."):console.log("==> Generated a new AUTH_SECRET via 'npx auth secret'.");let d={NEXT_PUBLIC_SITE_URL:m||r.NEXT_PUBLIC_SITE_URL||a,MONGODB_URI:c||r.MONGODB_URI||"",MONGODB_DB:s||r.MONGODB_DB||"portfolio",AUTH_SECRET:f,ADMIN_USERS_FILE:r.ADMIN_USERS_FILE||"",RESUME_CACHE_FILE:r.RESUME_CACHE_FILE||"",...l};p.mkdirSync(u.dirname(n),{recursive:!0}),h(n,d),console.log(`Saved ${i} (mode 600).`),d.MONGODB_URI||console.warn(`WARNING: MONGODB_URI is empty \u2014 edit ${i} before using it.`)}A();
